### ISSUE TITLE
Crash on Client after latest update with Geckolib (1.21.1 NeoForge)

### ISSUE THREAD

**Issue by dainekoichi** [LeoMinecraftModding/Eternal-Starlight#14]
I was able to launch it in a dedicated server, but on client it crashes. 
Logs attached: [crash-2024-09-28_11.25.45-client.txt](https://github.com/user-attachments/files/17172145/crash-2024-09-28_11.25.45-client.txt)

Eternal Starlight version: 0.1.14 (1.21.1)
Geckolib version: 4.6.6 (1.21.)

**Comment by LeoLezury** [comment]
Seems to be the same issue as #13 mentioned. Will fix in 0.1.15. Thanks for reporting

**Comment by LeoLezury** [comment]
Fixed in 0.1.15, uploaded on CurseForge
