### ISSUE TITLE
Rendering entity in world - Crash

### ISSUE THREAD

**Issue by SirTwsted** [LeoMinecraftModding/Eternal-Starlight#15]
Game Splash Screen Notice:
The game crashed whilst rendering entity in world
Error: java.lang.NullPointerException: Cannot invoke "net.minecraft.world.item.ItemStack.is(net.minecraft.tags.TagKey)" because "this.armorStack" is null

Here is the crash log:
https://pastebin.com/ra6X9FKv

I am using:
Minecraft v1.21.1
NEOForge v21.1.64
Eternal Starlight v0.1.14

I was forced to disable the mod after 17 days of gameplay.

Hope all is well.  😉👍

**Comment by LeoLezury** [comment]
it's already fixed on GitHub a few days ago but I haven't released a new version now. you can try the build output in the GitHub actions

**Comment by LeoLezury** [comment]
Fixed in 0.1.15, uploaded on CurseForge
