### ISSUE TITLE
Make the golem less oppressive

### ISSUE THREAD

**Issue by team1257Simon** [LeoMinecraftModding/Eternal-Starlight#16]
The down-period you get when you disable the power sources is way too short and the time you have to wait before you can damage it again is way too long. Bosses that spend 90% of their time invincible regardless of what the player does do not belong in any game, much less a sandbox game. Please change these timers to be more reasonable -- multiply the duration you have to hit it by 10, and divide the cooldown period on the power sources by like a hundred.

**Comment by LeoLezury** [comment]
I fought it myself and it seems to be quite easy to fight after 0.1.13, are you playing 0.1.13-? The boss structure in older versions made the boss very hard to defeat

**Comment by team1257Simon** [comment]
0.1.14.
It was actually less the structure itself and more the timings -- I didn't actually count it off like I probably should have, but I suppose I could find it in the code (it's not the precise numbers that are the point anyway).
Unless I was missing something, or there was some sort of bug or interaction with another mod, I only managed to get 2 hits in with a sword each time I disabled the invincibility, and then the period during which I couldn't bring it down again lasted at least a minute (which is far too long for a boss to be completely invincible in any game, full stop). 
Literally, I would swing like mad immediately when I got the chance, and the third hit would bounce.
It took me 5 cycles of this even with a sword I NBT edited to 100 levels of sharpness so that I could maybe not take forever at it...I've always had an intense distaste for boss fights that inflate their duration with invincibility mechanics, but this one was so egregious that I actually had to take the extra step of mentioning it to the developer on the GitHub because of how frustrating it was for me.
EDIT: the version I wrote is the version that's currently installed on my instance and (to the best of my ability to remember) the version I was playing when I wrote this. I am human, however, and may have updated it and then forgotten I updated it. Unlikely though.
EDIT 2: Okay, I looked and 600 ticks should be 30 seconds, which it most certainly did not give me. So it's possible that it might be a bugged interaction that caused the invulnerability to resume early -- that would be consistent with the fact that I couldn't disable the power source for about that much time. If there are hard limits on the amount of damage that it can take per time the power source is disabled, those need to be removed, because it's extremely frustrating for players when a fight artificially inflates its duration like that (as I previously mentioned).
EDIT 3: I realized this sounds pretty negative so I want to clarify -- I only got to this point because I thought the theme of this mod was really cool, and I wanted to engage with it. Overall it's been good, this was just one thing that I had to mention (it's not uncommon for something like this to irk me enough to complain about it somewhere, but I decided to use github this time because it was already open in my browser). 
The only other frustration I had was a crash someone else has already mentioned, so hopefully that will be fixed soon if it isn't already
Anyway...ye

**Comment by LeoLezury** [comment]
I increased the golem's charging time, hopefully the fight will be easier on 0.1.16, thanks for reporting :)

**Comment by LeoLezury** [comment]
Sorry but can you provide a crash log? Thank you very much. (Also, is the crash #18 ?)

**Comment by team1257Simon** [comment]
It's #12
The cast isn't by a mod. It's by the loader, in a function that the mod was calling but other mods might call. You should reopen that pull
