### ISSUE TITLE
Client side crash on Neoforge 1.21.1

### ISSUE THREAD

**Issue by dainekoichi** [LeoMinecraftModding/Eternal-Starlight#17]
[crash-2024-09-30_20.02.45-server.txt](https://github.com/user-attachments/files/17198451/crash-2024-09-30_20.02.45-server.txt)

**Comment by LeoLezury** [comment]
“java.lang.IllegalAccessError: failed to access class net.minecraft.client.renderer.BiomeColors from class com.hyperlynx.reactive.items.LitmusPaperItem” it seems to be the fault of the "reactive" mod?

**Comment by LeoLezury** [comment]
Oh I see please change your NeoForge version to 21.1.62+

**Comment by dainekoichi** [comment]
> Oh I see please change your NeoForge version to 21.1.62+

Thanks! Working now, you can close this if this is the best solution :)
