### ISSUE TITLE
extreme lag

### ISSUE THREAD

**Issue by 893203** [LeoMinecraftModding/Eternal-Starlight#25]
currently playing the modpack craftorio(1.6.1), running neo-forge 21.7.2.

the issue starts when I attempt to go inside the maze dungeon, outside, the fps is just fine. 

i suspect it has something to do with the following mods I added myself:
distant horizons (notably I did turn off rendering and try to set the distance to 0)
everlasting abilities (made sure i took away any ability that affected other creatures before entering)
Pickletweaks (nothing tried)
pufferfish skills/attributes (nothing tried)
default skill tree (related to pufferfish skills)
cyaneryth mob tree (also related to pufferfish)
overflowing bars

in my mind the most likely culprit is pufferfish skills but i dont know how to go into any sort of debug mode for this mod or view what is causing tps lag in minecraft.

**Comment by LeoLezury** [comment]
There're many block entites in the maze (Lunar Vine Block), maybe just use some block entity related optimization mod? The structure will be overhauled in a future update, it'll be smaller so these laggy vines will be less too.

**Comment by LeoLezury** [comment]
You can send a [spark](https://modrinth.com/mod/spark) log here

**Comment by LeoLezury** [comment]
Try update to the latest 0.1.18. The structure has been reworked with its size decreased. (Only works if you generate a new world)
