### ISSUE TITLE
Portal not rendered with Shaders (Neoforge 1.21.1)

### ISSUE THREAD

**Issue by ElTryken** [LeoMinecraftModding/Eternal-Starlight#27]
When shaders are enabled, the portal is not rendered and becomes invisible.

OFF:
![image](https://github.com/user-attachments/assets/5a47f943-6a65-4c69-b8ca-dac929fda2e2)
ON:
![image](https://github.com/user-attachments/assets/bdcac8de-88b7-4cbd-b362-32cabe023ffa)

**Comment by ElTryken** [comment]
I just find how to fix in config, my bad.

**Comment by NeillHub** [comment]
@ElTryken Hi, Could you tell me what you changed in the config?
