### ISSUE TITLE
Encountering/placing a gatekeeper on the server will result in an error message. The following is the error message

### ISSUE THREAD

**Issue by openthedoge** [LeoMinecraftModding/Eternal-Starlight#3]
[crash-2024-08-12_18.34.38-server.txt](https://github.com/user-attachments/files/16580436/crash-2024-08-12_18.34.38-server.txt)
If you can reproduce this error, please let me know. If this error is my own fault, then I can only regret giving up this mod

**Comment by LeoLezury** [comment]
Thanks for reporting the issue! But can you provider the _**latest.log**_ file, which is a more detailed and comprehensive log?

**Comment by LeoLezury** [comment]
Yes. It's the mod's problem. It'll be fixed in the next version, you can temporarily remove the mod now.

**Comment by LeoLezury** [comment]
Fixed in 0.1.4😎
