### ISSUE TITLE
Network implementation causing unnecessary lag

### ISSUE THREAD

**Issue by someaddons** [LeoMinecraftModding/Eternal-Starlight#37]
Hi, would be nice if you could improve this part of your code, its causing unnecessary lag since its searching all entities and sends packets all the time :)

Related code:
https://github.com/LeoMinecraftModding/eternal-starlight/blob/fc59edcd26bd8d5aa302d58d78b62c1b22d93265/common/src/main/java/cn/leolezury/eternalstarlight/common/handler/CommonHandlers.java#L99

From looking at your code it seems that you're only attaching the spellcaster interface to the player, in which case you could be just listening to the Player Tick event instead, and check `event.player instanceof Spellcaster`. 
If you need it for more entities than just players I'd recommend keeping a local list for the relevant entities, which gets filled by entity enter/leave world events (just on world enter check instanceof Spellcaster) 

Also you normally should not be sending a packet each tick, instead only send it when necessary, aka when your data changed, which can be achieve by a boolean toggle e.g. in the spellData which indicates that it requires syncing.

![image](https://github.com/user-attachments/assets/dcff88f1-7e48-49ce-90d4-819fddc8a3e8)

**Comment by LeoLezury** [comment]
ok I'll fix this soon, thanks for the detailed explanation :)
