### ISSUE TITLE
Music Disc Tags

### ISSUE THREAD

**Issue by TheBedrockMaster** [LeoMinecraftModding/Eternal-Starlight#38]
Add the `eternal_starlight:music_discs` item tag to the `c:music_discs` item tag.

**Comment by LeoLezury** [comment]
It's actually already there

**Comment by TheBedrockMaster** [comment]
It wasn't in the most recent release when I made this issue.

**Comment by LeoLezury** [comment]
Yep, I'll release 0.2.1 soon
