### ISSUE TITLE
"Eternal Starlight" causes massive lag when placing "Cooking For Blockheads" multi-kitchen blocks

### ISSUE THREAD

**Issue by YourfriendTutu** [LeoMinecraftModding/Eternal-Starlight#41]
Rundown: The involved mods can run together but placing a multi-kitchen block causes massive frame drops. For reference, I had 110 FPS and it dropped to 40 upon placing a fridge which is a 70 FPS loss. I also tested with the other multi-blocks and the same happened. Iris Shaders is also not the issue since I ran a separate build excluding Iris and the FPS loss still occurred.

Ver.: 1.21.1
Platform: Fabric 0.16.9

Mods(Dependencies included by not explicitly stated):
- Eternal Starlight
- Cooking For Blockheads
- Iris Shaders

Such a shame because I was updating my modpack for a server with friends and this mod's content was really cool but I cannot implement it because going near a multi-block will trap you in a google slideshow 😔

**Comment by YourfriendTutu** [comment]
Addtional Notes: From my tests, I've noticed these blocks causing the massive FPS loss. Intuitively, I would suspect that the colored variants also have the same issue so I tested a few for these blocks(but not every single one) and they seem to be having the FPS loss issue.
- Fridge
- Oven
- Sink
- Kitchen Counter
- Kitchen Cabinet
- Cow in a Jar

**Comment by LeoLezury** [comment]
Sorry for this, I'll try my best to fix this.

**Comment by YourfriendTutu** [comment]
No need for apologies. I am just happy that you responded and are looking into it. I also mentioned this thread and opened the issue in "Cooking For Blockheads" as well in case it could also be on their end. If they find anything, I can also share their findings here to help.

**Comment by YourfriendTutu** [comment]
On that note, another thing I noticed was the entity tick was extremely high near these blocks, up to 4000 entity ticks. It might have something to do with the kitchen block's multiscanning mentioned in the thread below. Perhaps something in "Eternal Starlight" is triggering the multi-blocks to generate massive entity ticks.
https://github.com/TwelveIterationMods/CookingForBlockheads/issues/675

**Comment by LeoLezury** [comment]
It's clear that Eternal Starlight caused the problem. It'll be fixed in the next version, tysm for reporting this! 
![spark analysis](https://github.com/user-attachments/assets/75c6f269-712c-4746-a996-217cc892af43)

**Comment by LeoLezury** [comment]
Fixed. Things'll be alright in the next version.
