### ISSUE TITLE
Attribute Load Order issue

### ISSUE THREAD

**Issue by Noaaan** [LeoMinecraftModding/Eternal-Starlight#7]
Originally found in https://github.com/Noaaan/MythicMetals/issues/259

The method which adds attributes for LivingEntities is cancellable, meaning depending on what order mods load in, it could cause attributes from other mods to be misisng.
https://github.com/LeoMinecraftModding/eternal-starlight/blob/adf37aab706cf92812cd5961a29b8d741914cc44/common/src/main/java/cn/leolezury/eternalstarlight/common/mixin/LivingEntityMixin.java#L69-L71

The fix for this is quite simple - adding to the return value simply works, as the map is mutable in this state.
See https://github.com/Noaaan/MythicMetals/blob/5673317bb5401a631db4c960b103e9e71339761e/src/main/java/nourl/mythicmetals/mixin/LivingEntityMixin.java#L98-L101

**Comment by LeoLezury** [comment]
Thanks for reporting! But it seems to be already fixed [here](https://github.com/LeoMinecraftModding/eternal-starlight/blob/1.21.X-Arch/common/src/main/java/cn/leolezury/eternalstarlight/common/mixin/LivingEntityMixin.java#L71). It should be fixed in 0.1.6.
