### ISSUE TITLE
Missing Item Tags

### ISSUE THREAD

**Issue by TheBedrockMaster** [LeoMinecraftModding/Eternal-Starlight#9]
The following items should have these item (and some also block) tags:

All 3 Pickaxes: `c:tool/mining_tool`
All 6 Swords: `c:tool/melee_weapon`
All 4 Axes: `c:tool/melee_weapon`
All 5 Bows and Crescent Spear: `c:tools/ranged_weapon`
Aethersent Ingot: `c:ingots/aethersent`
Aethersent Block: `c:storage_blocks/aethersent`
Aethersent Nugget: `c:nuggets/aethersent`
Raw Aethersent: `c:raw_materials/aethersent`
Raw Aethersent Block: `c:storage_blocks/raw_aethersent`
Amaramber Ingot: `c:ingots/amaramber`
Raw Amaramber: `c:raw_materials/amaramber`
Amaramber Nugget: `c:nuggets/amaramber`
Atalphaite Block: `c:storage_blocks/atalphaite`
Golem Steel Ingot: `c:ingots/golem_steel`
Oxidized Golem Steel Ingot: `c:ingots/oxidized_golem_steel`
Golem Steel Block: `c:storage_blocks/golem_steel`
Oxidized Golem Steel Block: `c:storage_blocks/oxidised_golem_steel`
Grimstone Atalphaite, Grimstone Redstone Ore, Grimstone Saltpeter Ore: `c:ores_in_ground/grimstone`
Voidstone Atalphaite, Voidstone Redstone Ore, Voidstone Saltpeter Ore: `c:ores_in_ground/voidstone`

**Comment by LeoLezury** [comment]
Fixed in 0.1.12🎉 Waiting for CurseForge to review the file
